---
apiVersion: v1
kind: Namespace
metadata:
  name: default-backend-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-backend-app
  namespace: default-backend-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: default-backend-app
  template:
    metadata:
      labels:
        app: default-backend-app
    spec:
      containers:
        - name: nginx-default-backend
          image: ghcr.io/vincepower/nginx-default-backend:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 500Mi
            requests:
              memory: 250Mi
---
apiVersion: v1
kind: Service
metadata:
  name: default-http-backend
  namespace: default-backend-ns
spec:
  selector:
    app: default-backend-app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: default-backend-ingress
  namespace: default-backend-ns
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
          - path: /b
            pathType: Prefix
            backend:
              service:
                name: default-http-backend
                port:
                  number: 80
